# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#
# default: &default
#   # adapter: sqlite3
#   # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   # timeout: 5000
#   adapter: mysql2
#   database: table_name
#   username: user
#   password: password
#   host: localhost
#   encoding: utf8


# for MySQL
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root      
  password: password
  host: localhost

development:
  <<: *default
  database: yourtravel_development

test:
  <<: *default
  database: yourtravel_test

production:
  <<: *default
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOSTNAME'] %>



# production:
#   # for heroku
#   <<: *default
#   adapter: postgresql
#   encoding: utf8
#   pool: 5
#   port: 5432
#   database: pg_production
#   url: <%= ENV['DATABASE_URL'] %>
